"""remove history.inn

Revision ID: 14d5d2a23f8a
Revises: 31def05fd292
Create Date: 2025-12-18 14:46:41.694293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14d5d2a23f8a'
down_revision: Union[str, None] = '31def05fd292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_history_inn'), table_name='history')
    op.drop_column('history', 'inn')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('inn', sa.VARCHAR(length=12), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_history_inn'), 'history', ['inn'], unique=False)
    # ### end Alembic commands ###
