"""add history.params

Revision ID: 31def05fd292
Revises: 9a7967e442cd
Create Date: 2025-12-18 10:23:21.206400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31def05fd292'
down_revision: Union[str, None] = '9a7967e442cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_unique_constraint(op.f('uq_history_id'), 'history', ['id'])
    op.create_unique_constraint(op.f('uq_organizations_id'), 'organizations', ['id'])
    op.create_unique_constraint(op.f('uq_reports_id'), 'reports', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_reports_id'), 'reports', type_='unique')
    op.drop_constraint(op.f('uq_organizations_id'), 'organizations', type_='unique')
    op.drop_constraint(op.f('uq_history_id'), 'history', type_='unique')
    op.drop_column('history', 'params')
    # ### end Alembic commands ###
