"""init

Revision ID: 9a7967e442cd
Revises: 
Create Date: 2025-12-17 11:06:43.554947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a7967e442cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=False),
    sa.Column('request', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_history')),
    sa.UniqueConstraint('id', name=op.f('uq_history_id'))
    )
    op.create_index(op.f('ix_history_inn'), 'history', ['inn'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('id', name=op.f('uq_organizations_id'))
    )
    op.create_index(op.f('ix_organizations_inn'), 'organizations', ['inn'], unique=True)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('report_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('present_date', sa.Date(), nullable=False),
    sa.Column('organization_sheet', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('balance_sheet', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('financial_sheet', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_reports_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports')),
    sa.UniqueConstraint('id', name=op.f('uq_reports_id'))
    )
    op.create_index(op.f('ix_reports_report_year'), 'reports', ['report_year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_report_year'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_organizations_inn'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_history_inn'), table_name='history')
    op.drop_table('history')
    # ### end Alembic commands ###
